### ISSUE TITLE
Handle empty files

### ISSUE THREAD

**Issue by cmeeren** [gonejack/transcode#5]
Empty files produce this:

```
2023/03/02 10:13:47 cannot determine source-encoding: cannot detect encoding: EOF
```

It would be nice if this tool output a more helpful message for empty files, e.g. "file is empty, ignoring". Because the above message indicates that something might be wrong.

See also #4.

**Comment by gonejack** [comment]
Hi, @cmeeren 

Version [v1.0.7](https://github.com/gonejack/transcode/releases/tag/v1.0.7) should be ignoring empty files as well as doing filename printing metioned in another thread.

**Comment by cmeeren** [comment]
That was quick! Thanks!
